config/routes.rb
Site::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  root :to => "users#new"
  resources :sessions

  resources :action_lists do
    member do
      post 'reset'
    end
    member do
      post 'execute'
    end
    member do
      post 'execute_rest'
    end
    member do
      post 'keystrokes'
    end
    member do
      post 'clear'
    end
    member do
      get 'status'
    end
    member do
      post 'delete_current_action_type'
    end
  end

  resources :action_types do
    collection do
      get 'select_changed'
    end
    collection do
      post 'create_current'
    end
  end

  resources :actions

  resources :users

  resources :data do
    collection do
      get 'select_changed'
    end
  end

end

app/views/shared/_content.html.erb
<% if @content.nil? or @content.empty?
   @content = "ERROR: no content"
end
%>

<%=
   if @highlight_length == 0
 h(@content).gsub("\n", "<br />").html_safe
else
   start = h(@content[0...@highlight_start])
   middle = h(@content[@highlight_start...(@highlight_start+@highlight_length)])
   last = h(@content[(@highlight_start+@highlight_length)..-1])
   
   display_content = start + "X<span class='highlight'>" + middle + "</span>" + last
   display_content.gsub("\n", "<br />").html_safe
end
 %>

app/views/shared/_content.json.erb
<%= 
@datum = @user_state.current_action_list.datum

{"content" => (render :partial => "shared/display_content.html.erb", :formats => ["html"], :handlers => ["erb"]),
            "info" => (render :partial => "shared/display_info.html.erb", :formats => ["html"], :handlers => ["erb"]),
	    "sidebar" => (render :partial => "shared/sidebar.html.erb", :formats => ["html"], :handlers => ["erb"])
}.to_json.html_safe
%>

app/views/shared/_display_content.html.erb
<%=

   tagger = Tagger.new(@user_state.temp_current_data)
   tagger.replace_spaces_with_tags
   if @user_state.temp_highlight_length != 0
     tagger.add_tags("<span class='highlight'>", @user_state.temp_highlight_start, 
                     "</span>", @user_state.temp_highlight_start + @user_state.temp_highlight_length)
   end

   if @user_state.last_mark_position != 0
     tagger.add_tags("<span class='mark'>", @user_state.current_position, "</span>", @user_state.last_mark_position)
   end

   tagger.add_tags("<span class='cursor'>|</span>", @user_state.current_position)
   tagger.display_content.html_safe
   
 %>

app/views/shared/_display_info.html.erb
<%=

ret = ("highlight_length = " + h(@user_state.temp_highlight_length.to_s) + ", index = " + h(@user_state.current_action_list_index.to_s) + ", position: " + h(@user_state.current_position.to_s))

if not @user_state.errors.nil?
   ret += "<br /><span class='error'>" + h(@user_state.last_errors.to_s) + "</span>"
end

ret.html_safe
%>

app/views/shared/_sidebar.html.erb
<%
user_state = current_user.nil? ? nil : current_user.user_state

index = user_state.nil? ? nil : user_state.current_action_list_index
count = @datum.action_list.action_types.count

action_types = @datum.action_list.action_types

%>

<b>Action Types</b><br />
<p>
<%= link_to 'New action', new_action_type_path(:action_list_id => @datum.action_list.id, :position => index) %>

</p>

<p>
<%= link_to "Execute one at a time (ctrl+e)", url_for(:controller => :action_lists, :action => :execute, :id => @datum.action_list.id), :remote => true, :id => "execute_link", :method => :post %>
</p>
<p>
<%= link_to "Execute rest of list", url_for(:controller => :action_lists, :action => :execute_rest, :id => @datum.action_list.id), :remote => true, :id => "execute_rest_link", :method => :post %>
</p>
<div id="record_keystrokes_div">
  <a href="#" onclick="return false;" id="record_keystrokes_link">Record keystrokes (ctrl+r)</a>
</div>
<%= 
# a hidden form so that javascript knows the correct keystrokes id
form_tag(url_for(:controller => :action_lists, :action =>:keystrokes, :id => @datum.action_list.id), :id => "record_keystrokes_hidden_form")  do %>
<% end %>
<%=
form_tag(url_for(:controller => :action_types, :action => :create_current), :id => "search_url_hidden_form") do
%>
<% end %>
<%= 
      form_tag(url_for(:controller => :action_lists, :action => :delete_current_action_type, :id => @datum.action_list.id), :id => "delete_action_hidden_form") do %>
<% end %>
<p>
<%= link_to "Reset", url_for(:controller => :action_lists, :action => :reset, :id => @datum.action_list.id), :remote => true, :id => "reset_selected", :method => :post %>
</p>
<p>
<%= link_to "Clear", url_for(:controller => :action_lists, :action =>:clear, :id => @datum.action_list.id), :remote => true, :id => "clear_link", :confirm => "Are you sure you want to clear the action types?", :method => :post %>
</p>

<ol>
<% 
action_types.count.times do |i|
  action_type = action_types[i] 
  selected = nil
  selected_string = ""

  if not user_state.nil? and user_state.current_action_list_id == @datum.action_list.id and (index == i or (index == count and i == count - 1))
    selected = true
    selected_string = if index == count
                        "<div class='selected_bottom'>"
                      else
                        "<div class='selected'>"
                      end
  end
 %>
<li>
<%= (selected_string).to_s.html_safe %>
   <%= link_to action_type.describe, url_for(:controller => :action_types, :action => :edit, :id => action_type.id) %>
   <%= link_to "X", url_for(:controller => :action_types, :action => :destroy, :id => action_type.id) %>
<%= ("</div>" if selected).to_s.html_safe %>
</li>
<% end %>
</ol>

<script type="text/javascript">
$(document).ready(function() {

    bind_record_keystrokes();
});
</script>