config/routes.rb
Site::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  root :to => "users#new"
  resources :sessions

  resources :action_lists do
    member do
      post 'reset'
    end
    member do
      post 'execute'
    end
    member do
      post 'execute_rest'
    end
    member do
      post 'keystrokes'
    end
    member do
      post 'clear'
    end
    member do
      get 'status'
    end
    member do
      post 'delete_current_action_type'
    end
  end

  resources :action_types do
    collection do
      get 'select_changed'
    end
    collection do
      post 'create_current'
    end
  end

  resources :actions

  resources :users

  resources :data do
    collection do
      get 'select_changed'
    end
  end

end

app/controllers/data_controller.rb
class DataController < ApplicationController
  # GET /data/1
  # GET /data/1.json
  def show
    @datum = Datum.find(params[:id])

    if not current_user.nil? and @datum.action_list.id == current_user.user_state.current_action_list_id and not current_user.user_state.temp_current_data.nil?
      @user_state = current_user.user_state
    else
      @user_state = UserState.new
      @user_state.reset(@datum.action_list.id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datum }
    end
  end

  # GET /data/new
  # GET /data/new.json
  def new
    @datum = Datum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datum }
    end
  end

  # GET /data/1/edit
  def edit
    @datum = Datum.find(params[:id])
    switch_action_list(@datum.action_list.id)
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(params[:datum])
    @datum.action_list = ActionList.new(:name => "Empty")
    @datum.action_list.datum = @datum
    @datum.user = current_user
    @user_state = current_user.user_state
    respond_to do |format|
      if not @datum.action_list.save
        format.html { render action: "new" }
        format.json { render json: @datum.action_list.errors, status: :unprocessable_entity }
      elsif not @datum.save
        format.html { render action: "new" }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      else
        @user_state.reset(@datum.action_list.id)

        if not @user_state.save
          format.html { render action: "new" }
          format.json { render json: @user_state.errors, status: :unprocessable_entity }

        else
          format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
          format.json { render json: @datum, status: :created, location: @datum }
        end
      end
    end
  end
  
  # PUT /data/1
  # PUT /data/1.json
  def update
    @datum = Datum.find(params[:id])
    verify_user(@datum.user.id)

    action_list = @datum.action_list
    switch_action_list(action_list.id)

    respond_to do |format|
      if @datum.update_attributes(params[:datum])
        @datum.user.user_state.reset(action_list.id)
        if not @datum.user.user_state.save
          format.html { render action: "edit" }
          format.json { render json: @datum.user.user_state.errors, status: :unprocessable_entity }
        else          
          format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum = Datum.find(params[:id])
    verify_user(@datum.user.id)
    @datum.destroy

    respond_to do |format|
      format.html { redirect_to data_url }
      format.json { head :no_content }
    end
  end

  def select_changed
    @datum = Datum.find_by_id(params[:id])
    if @datum.nil?
      @datum = Datum.new
    end
    @datum.source_type = params[:datum][:source_type]
    if @datum.source_type.nil? or @datum.source_type.empty?
      @datum.source_type = "from_clip"
    end

    respond_to do |format|
      format.html {
        render :partial => true
      }
    end
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_for @datum do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>:
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :source_type %>: 
    <%= select_tag "datum[source_type]", options_for_select(Datum::SourceTypes, @datum.source_type),
    :'data-remote' => 'true',
    :'data-url' => url_for(:controller => :data, :action => :select_changed, :id => @datum.id),
    :'data-type' => 'html'
%>

  </div>
  <div class="field" id="content_text">
    <%=
 render "select_changed" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data/_select_changed.html.erb
<%= fields_for @datum do |f| %>
<% source_type = f.object.source_type %>
<% if source_type == "from_clip" or source_type.nil? or source_type.empty? %>
<%= f.label :content, "Content" %><br />
<%= f.text_area :content %>
<% elsif source_type == "download_url" or source_type == "live_url" %>
<%= f.label :content, "URL" %>: 
<%= f.text_field :url %>

<% end %>
<% end %>

app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<span class="title"><%= link_to @datum.user.name, @datum.user %>'s data piece</span>
<div id="container">

<div id="info">
  <%= render "shared/display_info" %>
</div>

<div id="content">
  <%= render "shared/display_content" %>
</div>

<div id="sidebar">

  <%= render "shared/sidebar" %>
</div>  

</div>

<%= link_to 'Edit', edit_datum_path(@datum) %>