config/routes.rb
Site::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  root :to => "users#new"
  resources :sessions

  resources :action_lists do
    member do
      post 'reset'
    end
    member do
      post 'execute'
    end
    member do
      post 'execute_rest'
    end
    member do
      post 'keystrokes'
    end
    member do
      post 'clear'
    end
    member do
      get 'status'
    end
    member do
      post 'delete_current_action_type'
    end
  end

  resources :action_types do
    collection do
      get 'select_changed'
    end
    collection do
      post 'create_current'
    end
  end

  resources :actions

  resources :users

  resources :data do
    collection do
      get 'select_changed'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Macrovator</title>
  <link href='http://fonts.googleapis.com/css?family=Asap:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="login">
  <% if current_user %>
  Logged in as <%= link_to current_user.name, :controller => :users, :action => :show, :id => current_user.id %>
  <%= link_to "Log out?", log_out_path %>
  <% else %>

  <%= link_to "Log in", log_in_path %>
  <%= link_to "Register", new_user_path %>
  <% end %>
</div>
<div id="wrap">
<%= yield %>
</div>
</body>
</html>